### ISSUE TITLE
Strange behaviour with Elegoo Mars

### ISSUE THREAD

**Issue by sixtemesseven** [Photonsters/PhotonFileEditor#103]
I tried inserting a png image into a template print to expose a PCB.

I tried this:
1. Make a project with elegoo mars in chiTuBox v1.5.0
2. Renaming it to .photon
3. Opened it in photon editor and replaced a layer with my 1440x2460 png file
4. Saved as .photon
5. renamed to cbddlp
6. Tried to print

The printer will start, but it will display a image from the last print job and not continioue with printing but it will get stuck...

This is my result when I replace layer 2 in the PE:
![imageOfPhotonEditor](https://user-images.githubusercontent.com/5941270/63650680-9d7af100-c74d-11e9-8ae3-6bf614125302.JPG)

Onother thing is when I try to open the modified .photon with the PCB layer and saved as new .photon file once more in the photon editor I get this message:
Index -1 is out of bounds for axis 0 with size 0

Here are my .photon files which I experimented with:
[MyPrints.zip](https://github.com/Photonsters/PhotonFileEditor/files/3538166/MyPrints.zip)

Here is my png file:
![layer](https://user-images.githubusercontent.com/5941270/63650664-53920b00-c74d-11e9-9109-fa34c0aa9da0.png)

**Comment by NardJ** [comment]
Hi development of PhotonFileEditor (v1) is halted. I am currently fixing multiple issues in Photonsters/Photonsters-FileEditor-v2. 

With the lastest alpha version I made the attached photon file.
[ReplacePcbPngOnLayer0_NewFile.photon.zip](https://github.com/Photonsters/PhotonFileEditor/files/3538231/ReplacePcbPngOnLayer0_NewFile.photon.zip)
Can you check if this file works correctly?
(You should probably fix 'Exp. bottom (s)')

To reproduce: 
o Saved png file in your message above, 
o started PFEv2, select [File>New], 
o [Layers>Replace Image],  select saved png file
o [File>Save]

![image](https://user-images.githubusercontent.com/11459480/63651750-9c9b8c80-c758-11e9-8f1e-1e0d812d4f5b.png)

**Comment by sixtemesseven** [comment]
Yes, this worked perfectly!
I was also able to run the source! Thanks!
