### ISSUE TITLE
How to protect Master from commits

### ISSUE THREAD

**Issue by NardJ** [Photonsters/PhotonFileEditor#51]
I am searching the web how to protect the master branch from (accidental) commits by myself. I want the commits to be to another development branch which will eventually be merged. However I can't find anything usefull.

I found the setting Branch Protection for master, however as I understand this only protects from merges and not from commits. Any ideas?

![image](https://user-images.githubusercontent.com/11459480/41984961-44d8df4e-7a32-11e8-86e6-ccab6d0cfd89.png)

**Comment by X3msnake** [comment]
Just activate Require Pull request reviews. You can override the pull request with your admin but you get a red warning

**Comment by NardJ** [comment]
thx, turned it on!
