### ISSUE TITLE
Bo Nørgaard optimization preview reader

### ISSUE THREAD

**Issue by NardJ** [Photonsters/PhotonFileEditor#61]
Bo Nørgaard: 
> Btw, as mentioned above, I did some optimisations in the preview reader that can be easily ported to the file utility app

![image](https://user-images.githubusercontent.com/11459480/42468452-426c28a6-83b5-11e8-8fd4-a77388888bd0.png)

**Comment by X3msnake** [comment]
@NardJ 

Have you had time to implement @bonosoft sugested optimizations?

**Comment by NardJ** [comment]
Implemented in OpenGL2 branch
