### ISSUE TITLE
Algorithm needed to hollow model

### ISSUE THREAD

**Issue by NardJ** [Photonsters/PhotonFileEditor#63]
I am in need of a good algorithm to hollow out models. Or to put it differently to make a model of the inner cavity. Approaches I am trying:
- displace point of original model in the inverse direction of the triangle normal
- place a sphere at the center and displace point of sphere outwards until minimal distance to points of model are reached.

Any ideas what a good but simple approach is? In my opnion the reason for hollowing is saving resin, so it does not have to be perfect, but speed is important.

**Comment by X3msnake** [comment]
@Antharon @Reonarudo @Rob2048

**Comment by X3msnake** [comment]
@NardJ  

Maybe it is easyer to do with the sliced model. take the pixel edge and count pixels in?

Or check Meshlad solution, it's open source so we can use it
http://www.meshlab.net/

**Comment by NardJ** [comment]
Implemented in Ivan's branch with gyroid infill.
