### ISSUE TITLE
Add layer image editing 

### ISSUE THREAD

**Issue by NardJ** [Photonsters/PhotonFileEditor#64]
Make it possible to touch up layer images and possibly edit multiple layers at the same time.

**Comment by NardJ** [comment]
@Photonsters/photon-file-editor Just implemented basic layer editing (coloring pixels) in the OpenGL branch. Just wondering what needs to be added to make this fully usable. Some ideas, but please add to them or strike them if unnecessary:
- Show lower layers as reference
- Color pixels from current layer to buttom layer (for making a support column)
- Multiple brushes, e.q. cylinder to bottom, small to large diameter towards bottom, draw angled to bottom
- Undo 

![image](https://user-images.githubusercontent.com/11459480/42779821-d034389a-8941-11e8-90ef-87b0fce4f83d.png)

**Comment by X3msnake** [comment]
Onion Skinning slider

![image](https://user-images.githubusercontent.com/11083514/42788189-ec921b88-8955-11e8-8c10-0c590477dcd7.png)

**Comment by NardJ** [comment]
Implemented in OpenGL2 branch. The shadow layers of lower layers do not scale properly yet and should have different color to distinguish from the current layer.

**Comment by NardJ** [comment]
Now fully implemented in OpenGL2 branch. Loading shadow layers is still a bit to slow, will work better if parallel processing is used. (#66)
