### ISSUE TITLE
Add a fix my layer height button/action (floating point problem) 

### ISSUE THREAD

**Issue by X3msnake** [Photonsters/PhotonFileEditor#71]
![image](https://user-images.githubusercontent.com/11083514/43050109-ab445efc-8dfb-11e8-97db-cbc60933e5ec.png)

Based on [this](https://www.facebook.com/groups/1194619320682708/admins/) and [this](https://www.facebook.com/groups/AnycubicPhoton/permalink/1397710053706966/) FB thread it would be great to have a quick fix button to stabilize the floater numbers intruduced by the slicer untill Chitu releases a fixed version of this issue.

**Comment by NardJ** [comment]
If I understand correctly: The slicer does not round the layer height so it becomes something like 0.049999 instead op 0.05. This error accumulates since the cumulative layerheight is build adding 0.049999 to the previous layerheight instead of multiplying 0.05 to the layer Nr?

**Comment by NardJ** [comment]
Is there a set op optimal layer height for the stepper motor in the Photon? In the docs section I see:

> MOTION DRIVER / MECHANICS
    T8 leadscrew with 2mm lead/pitch
    Nema 17 Motor 1.8º 200steps/rev
    Driver embeded Polulu Alegro 4998 set at 1/16 microstepping
    Hardware resolution 10µ (0.01mm)
    Digital microstepped resolution 0.625µ (0.000625mm)

Motor step is 0.01mm, so multiples of 0.01mm are valid and anything deviating from this will give artifacts in the prints?

**Comment by NardJ** [comment]
I have implemented a check (tools menu in OpenGL2 branch) which checks if layerheight deviate from 0.01mm and a check if the cumulative layerheight deviates from layerNr*layerheight. After the check you can click ok to apply corrections.

**Comment by X3msnake** [comment]
@NardJ 

If the value is 0.005 it will put the motor in strain but half step is doable.
