### ISSUE TITLE
https://github.com/Photonsters/PhotonFileEditor/blob/master/GUI.py

### ISSUE THREAD

**Issue by X3msnake** [Photonsters/PhotonFileEditor#72]
Master branch
![image](https://user-images.githubusercontent.com/11083514/43199862-4bfe2ad8-900b-11e8-9d53-acfda4da33e6.png)

OpenGL2
![image](https://user-images.githubusercontent.com/11083514/43200017-d83e57de-900b-11e8-9dc2-549dfda1c1c7.png)

By @joaocarvalhoopen request i'm oppening this issue here.

He detected that in the above lines there is a extra + that might be unintended

**Comment by NardJ** [comment]
Thx and fixed in OpenGl2 branch!
